name: TEST Pipeline

on:
  push:
    branches: [ "main-test" ]

permissions: write-all

jobs:

  selenium-test:
    runs-on: windows-latest

    steps:
      - name: Checkout in main-test branch
        uses: actions/checkout@v4
        with:
          ref: "main-test"
          token: ${{ secrets.TEST_WRITE_ACCESS}}
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Setup Chrome stable version 119
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - run: chrome --version

      - name: Run the app
        run: |
          python app.py &

      - name: Test with pytest
        run: |
          python -m pytest tests/test_selenium.py  --html=selenium-test-report.html

      - name: Upload Selenium Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Selenium-testing-results-pytest-selenium
          path: |
             selenium-test-report.html
             Selenium_tests_screenshots


  push-main-test-branch-to-prod-repo:
    needs:
      - selenium-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code for conflict resolution branch
        uses: actions/checkout@v4
        with:
          ref: "conflict-resolution"
          token: ${{ secrets.TEST_WRITE_ACCESS}}

      - name: Merge import-dev with conflict-resolution
        run: |
         git merge import-dev
         git merge --strategy=ours --allow-unrelated-histories after-security



      - name: Add prod repo and push to prod repo

        run: |
          git remote add prod https://github.com/Code-Crusaders-DSU/Prod-Flashcard-Generator-WebApp
          git config user.name Niharika-R5
          git config user.email eng21ct0028@dsu.edu.in
          git push --force prod after-security:import-test
         


       
      
          
